name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - id: env
      run: cat .env >> $GITHUB_OUTPUT

    - name: Docker Login
      uses: docker/login-action@v3.3.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3.9.0

    - name: Build and push Docker images
      uses: docker/build-push-action@v6.13.0
      with:
        cache-from: type=gha
        cache-to: type=gha,mode=max
        push: true
        tags: |
          ghcr.io/${{ github.repository }}:latest
          ghcr.io/${{ github.repository }}:${{ steps.env.outputs.CODENAME }}
          ghcr.io/${{ github.repository }}:${{ steps.env.outputs.VERSION }}
